"""ORM models. Importing this package registers every table on ``Base.metadata``."""

from app.models.enums import (
    DEFAULT_DURATION,
    DURATION_CHOICES,
    AnswerReveal,
    AssignmentStatus,
    AttemptStatus,
    DeliveryMode,
    Difficulty,
    FileType,
    GenerationStatus,
    MaterialStatus,
    ParticipationStatus,
    QuestionOrigin,
    QuestionStatus,
    SourceKind,
    TestAudience,
    TestDifficulty,
    TestStatus,
    UserRole,
    UserStatus,
)
from app.models.material import Material, News, SourceChunk
from app.models.question import Question, Topic
from app.models.setting import BotSetting
from app.models.test import (
    GroupQuestionMessage,
    GroupTestPost,
    QuestionOption,
    Test,
    TestAssignment,
    TestAttempt,
    TestMaterial,
    TestQuestion,
    TestSource,
    UserAnswer,
)
from app.models.user import Group, GroupMember, User

__all__ = [
    "DEFAULT_DURATION",
    "DURATION_CHOICES",
    "AnswerReveal",
    "AssignmentStatus",
    "AttemptStatus",
    "BotSetting",
    "DeliveryMode",
    "Difficulty",
    "FileType",
    "GenerationStatus",
    "Group",
    "GroupMember",
    "GroupQuestionMessage",
    "GroupTestPost",
    "Material",
    "MaterialStatus",
    "News",
    "ParticipationStatus",
    "Question",
    "QuestionOption",
    "QuestionOrigin",
    "QuestionStatus",
    "SourceChunk",
    "SourceKind",
    "Test",
    "TestAssignment",
    "TestAttempt",
    "TestAudience",
    "TestDifficulty",
    "TestMaterial",
    "TestQuestion",
    "TestSource",
    "TestStatus",
    "Topic",
    "User",
    "UserAnswer",
    "UserRole",
    "UserStatus",
]
